Add KamajiControlPlaneTemplate for ClusterClass support
clastix/cluster-api-control-plane-provider-kamaji pull request #107
Opened 2024-06-04 13:42 UTC by chess-knight

Files were generated by `kubebuilder create api --group controlplane --version v1alpha1 --kind KamajiControlPlaneTemplate` and modified according to other providers and CAPI docs.
It means that `KamajiControlPlaneTemplate.spec.template.spec` = `KamajiControlPlane.spec(w/o replicas & version)`

2024-06-04 14:00 UTC, prometherion requested changes
Hey @chess-knight, this is a very nice and helpful implementation, thanks for it!

Let me know if you're up to the minor changes in your code, otherwise, happy to jump on it and co-author.

2024-06-04 14:00 UTC, prometherion commented on config/rbac/kamajicontrolplanetemplate_editor_role.yaml
> +  - get
Do we really need this role? Is it a result of scaffolding by kubebuilder/operator-sdk?

2024-06-05 05:51 UTC, chess-knight commented on config/rbac/kamajicontrolplanetemplate_editor_role.yaml
> +  - get
Yes, this is a result of Kubebuilder.

2024-06-05 06:34 UTC, chess-knight commented on api/v1alpha1/kamajicontrolplanetemplate_types.go
> +}
Hi, thank you for the review.
As I wrote in the PR description, `KamajiControlPlaneTemplateResourceSpec` is copied and pasted from KamajiControlPlaneSpec with removed Replicas and Version fields. I followed https://github.com/kubernetes-sigs/cluster-api/blob/main/controlplane/kubeadm/api/v1beta1/kubeadmcontrolplanetemplate_types.go#L72 and also found it e.g. in https://github.com/k3s-io/cluster-api-k3s/blob/main/controlplane/api/v1beta2/kthreescontrolplanetemplate_types.go#L38.
I agree, we can use KamajiControlPlaneSpec directly(e.g. `` Spec       KamajiControlPlaneSpec `json:"spec"` ``) instead of `KamajiControlPlaneTemplateResourceSpec` or use something more advanced.
AFAIK, the only required fields are *DataStoreName* and *Version*.

Please feel free to jump in for the minor changes, or we can talk about it right here and I will make changes - it's up to you.

2024-06-05 09:48 UTC, prometherion commented on api/v1alpha1/kamajicontrolplanetemplate_types.go
> +}
Thanks, @chess-knight!

I just force-pushed with the struct embedding, linter and manifests seem unchanged.

May I ask you for a final review so we can get this merged?

2024-06-05 10:34 UTC, chess-knight commented on api/v1alpha1/kamajicontrolplanetemplate_types.go
> +}
It looks good(and better) to me now, thanks!
I found only one typo in the commit message `introucing`.
We can merge it then.

2024-06-05 17:26 UTC, merged