Automatic creation of a release
clastix/cluster-api-control-plane-provider-kamaji pull request #18
Opened 2023-06-28 16:16 UTC by ptx96

Closes #14

2023-06-28 16:30 UTC, prometherion requested changes

2023-06-28 16:30 UTC, prometherion commented on .github/workflows/release.yaml
> +    runs-on: ubuntu-20.04
Let's use 22.04, if available.

2023-06-28 16:34 UTC, ptx96 commented on .github/workflows/release.yaml
> +    runs-on: ubuntu-20.04
All our workflows are using 20.04 :

- https://github.com/clastix/cluster-api-control-plane-provider-kamaji/blob/master/.github/workflows/ci.yaml#L11
- https://github.com/clastix/cluster-api-control-plane-provider-kamaji/blob/master/.github/workflows/docker-ci.yaml#L10

we should also change them

2023-06-28 16:56 UTC, prometherion reviewed
It would be perfect if we could complete the release process if and only if the CI workflow is completed, especially for the [diff stage](https://github.com/clastix/cluster-api-control-plane-provider-kamaji/blob/3a1176a161dc7854a6e957b6deccc3fa73a40a68/.github/workflows/ci.yaml#L30-L48).

It seems possible thanks to [workflow_run](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run), may I ask you to investigate it?

2023-06-28 18:59 UTC, ptx96 commented
> It would be perfect if we could complete the release process if and only if the CI workflow is completed, especially for the [diff stage](https://github.com/clastix/cluster-api-control-plane-provider-kamaji/blob/3a1176a161dc7854a6e957b6deccc3fa73a40a68/.github/workflows/ci.yaml#L30-L48).
> 
> It seems possible thanks to [workflow_run](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run), may I ask you to investigate it?

The [workflow_run](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run) feature allows you to run workflows in a chain, but the [diff stage](https://github.com/clastix/cluster-api-control-plane-provider-kamaji/blob/3a1176a161dc7854a6e957b6deccc3fa73a40a68/.github/workflows/ci.yaml#L30-L48) and the release one are triggered by different conditions (branches and tags);

the tag is created from the master branch and the code, to be merged to the master branch, must have passed the diff stage, so I don’t understand why bind them like this.

---

If we have to do a second check, we could move the diff stage to another workflow file, add the keyword "on: workflow_call:" and recall it as below within the release.yaml :

```
[...]

jobs:
  verify:
    uses: ptx96/cluster-api-control-plane-provider-kamaji/.github/workflows/diff.yaml@master

  release:
    name: tag release
    needs: verify # <--- the release job would only happen if the re-execution of the diff job (from the master) was successful
    runs-on: ubuntu-22.04

[...]
```

2023-06-28 20:12 UTC, ptx96 commented
> It would be perfect if we could complete the release process if and only if the CI workflow is completed, especially for the [diff stage](https://github.com/clastix/cluster-api-control-plane-provider-kamaji/blob/3a1176a161dc7854a6e957b6deccc3fa73a40a68/.github/workflows/ci.yaml#L30-L48).
> 
> It seems possible thanks to [workflow_run](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run), may I ask you to investigate it?

The [workflow_run](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run) feature allows you to run workflows in a chain, but the [diff stage](https://github.com/clastix/cluster-api-control-plane-provider-kamaji/blob/3a1176a161dc7854a6e957b6deccc3fa73a40a68/.github/workflows/ci.yaml#L30-L48) and the release one are triggered by different conditions (branches and tags);

the tag is created from the master branch and the code, to be merged to the master branch, must have passed the diff stage, so I don’t understand why bind them like this.

---

Anyway, if we REALLY have to do a second check, I was thinking about 2 different ways:

<details>
  <summary>1. Re-execute only diff stage BEFORE release</summary>

- Move the diff stage to another workflow file and add:

```yaml
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - requested
  workflow_call:
  ```

then, recall it as below within the release.yaml :

```yaml
[...]

jobs:
  verify:
    uses: ptx96/cluster-api-control-plane-provider-kamaji/.github/workflows/diff.yaml@master

  release:
    name: tag release
    needs: verify # <--- The release job would only happen if the re-execution of the diff job (from the master) was successful
    runs-on: ubuntu-22.04

[...]
```

I tried that and it works

commit: https://github.com/clastix/cluster-api-control-plane-provider-kamaji/compare/master...ptx96:cluster-api-control-plane-provider-kamaji:master
action: https://github.com/ptx96/cluster-api-control-plane-provider-kamaji/actions/runs/5405005059
</details>

Or

<details>
  <summary>2.Query Github API</summary>

- Use tag SHA to find the last status of the diff job for the master branch

```bash
export GITHUB_TOKEN="<REDACTED>"
export GITHUB_REPO="ptx96/cluster-api-control-plane-provider-kamaji"
export GITHUB_WORKFLOW="diff.yaml"
export HEAD_SHA="1b13057825a2a230e808e359d186a7b36a2ba5bb"

curl -sL \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer $GITHUB_TOKEN"\
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/$GITHUB_REPO/actions/workflows/$GITHUB_WORKFLOW/runs \
  | jq --arg input_sha "$HEAD_SHA" '.workflow_runs[] | select(.head_sha == $input_sha) | .conclusion'

"success"
```
  
</details>

2023-06-30 18:33 UTC, prometherion requested changes
In regards to the discussion started [here](https://github.com/clastix/cluster-api-control-plane-provider-kamaji/pull/18#issuecomment-1612039136):
> the tag is created from the master branch and the code, to be merged to the master branch, must have passed the diff stage, so I don’t understand why bind them like this.

You're totally right, as well as there's no need to install Go and issue the `make release` since the files will be already committed, thus there's no need to check any _diff_.

Please, remove the unrequited steps so we can merge this.

2023-06-30 18:33 UTC, prometherion commented on .github/workflows/release.yaml
> +          CGO_ENABLED: 0
There's no need to recreate the `config/control-plane-components.yaml` file since it should be already committed.

2023-07-01 10:16 UTC, ptx96 commented on .github/workflows/release.yaml
> +          CGO_ENABLED: 0
done

2023-07-01 11:56 UTC, prometherion approved these changes

2023-07-01 11:56 UTC, merged