allow overriding secretKey for kubeconfig
clastix/cluster-api-control-plane-provider-kamaji pull request #78
Opened 2024-02-04 23:01 UTC by kvaps

2024-02-05 04:47 UTC, prometherion requested changes
If we could take advantage of constants, it would be much better, wondering why I didn't do from.the beginning.

2024-02-05 04:47 UTC, prometherion commented on controllers/kamajicontrolplane_controller_resources.go
> +			for k, v := range cluster.GetAnnotations() {
There's no need to iterate over the map: just check if the key exists, and then return it, something as:

```go
v, ok := cluster.GetAnnotations()["kamaji.clastix.io/kubeconfig-secret-key"]
if ok && v != "" {
  secretKey = v
}
```

2024-02-05 08:47 UTC, kvaps commented
Ah that was just a draft, thanks for your corrections. PR updated and ready for review.

2024-02-08 18:35 UTC, prometherion commented
I'm thinking of the use case you're trying to solve, here, also considering the discussion we had on [Slack](https://kubernetes.slack.com/archives/C03GLTTMWNN).

Don't you think it would be better to have the TenantControlPlane exposed using the `ClusterIP` and provisioning manually (or via a third-party integration) the `kubeconfig` as well as the Ingress object to access it externally?

I'm a bit worried about the too many knobs we could introduce: although you know what you're doing other users could be able to shoot themselves in the foot, and this is something that must be carefully prevented to ensure the onboarding process works as expected.

Happy to chat.

2024-02-10 17:58 UTC, kvaps commented
Sure, it's open for discussion.

I suggested using an annotation because this setup might be uncommon.

Alternatively, I think we can introduce an option that will be completely understandable to everyone.

For example, `spec.network.preferLocalEndpoints: <true|false>`.

What do you think?

2024-02-22 17:22 UTC, andreykont commented
Hello. I like this PR. Because I would prefer use super-admin.conf as generic kubeconfig (based on 'system:master' Group to prevent losing access capi to managed kubernetes clusters)

2024-02-26 20:35 UTC, prometherion commented
@kvaps if we get clastix/kamaji#408 merged first, we could reuse the constant defined in the root repository.

Overall, LGTM.

2024-04-22 09:35 UTC, kvaps commented
@prometherion PR rebased. But now it depends on imported lib, so please review and merge https://github.com/clastix/cluster-api-control-plane-provider-kamaji/pull/93 first

2024-04-22 16:43 UTC, prometherion commented
@kvaps merged, please, rebase so we can use the last code base from Kamaji, thanks!

2024-04-22 17:20 UTC, kvaps commented
job is done

2024-04-23 09:04 UTC, prometherion approved these changes

2024-04-23 09:05 UTC, merged